apiVersion: v1
kind: Service
metadata:
  name: speedtest-server-service
spec:
  selector:
    app: speedtest-server
  ports:
    - name: tcp
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: udp  
      protocol: UDP
      port: 5201
      targetPort: 5201
  type: ClusterIP
